---

- name: EDPM Leapp OS Upgrade
  hosts: "{{ edpm_override_hosts | default('edpm_leapp_nodes', true) }}"
  strategy: linear
  gather_facts: true
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  environment: "{{ edpm_playbook_environment | default({}) }}"
  tasks:
    - name: Import edpm_leapp_upgrade role
      ansible.builtin.include_role:
        name: osp.edpm.edpm_leapp_upgrade
      tags:
        - edpm_leapp_upgrade
